"""Add AppState

Revision ID: 15704ba17c14
Revises: 4da480c8aed5
Create Date: 2020-01-16 02:26:35.098439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15704ba17c14'
down_revision = '4da480c8aed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('state', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('modifiedTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_state')
    # ### end Alembic commands ###
